/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.iggy.serde;

import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufUtil;
import io.netty.buffer.Unpooled;
import org.apache.iggy.exception.IggyInvalidArgumentException;
import org.apache.iggy.exception.IggyMalformedResponseException;
import org.apache.iggy.message.BigIntegerMessageId;
import org.apache.iggy.message.HeaderKey;
import org.apache.iggy.message.HeaderValue;
import org.apache.iggy.message.Message;
import org.apache.iggy.message.MessageHeader;
import org.junit.jupiter.api.Test;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Golden vectors generated by the Rust implementation: the batch encoded for
 * {@code SendMessages} and the poll body serving it back.
 */
class MessagesBatchWireFormatTest {

    private static final String PRODUCE_BATCH_ONLY =
            "000000000000000000000000000000000000000000000000e8030000000000008c01000000000000a91f38c86307267c02000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000bfd2b9205a759675070000000000000000000000000000000000000000000000000000000d000000000000000000000066697273742d7061796c6f6164d66b7e1c758eb7c0080000000000000000000000000000000100000032000000110000000e00000000000000000000007365636f6e642d7061796c6f6164757365722d6865616465722d6279746573";

    private static final String POLL_BODY =
            "03000000650000000000000002000000030000000000000064000000000000008813000000000000e8030000000000008c01000000000000c96826b38a8feed202000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000bfd2b9205a759675070000000000000000000000000000000000000000000000000000000d000000000000000000000066697273742d7061796c6f6164d66b7e1c758eb7c0080000000000000000000000000000000100000032000000110000000e00000000000000000000007365636f6e642d7061796c6f6164757365722d6865616465722d6279746573";

    @Test
    void shouldEncodeGoldenProduceBatch() {
        var messages = List.of(
                new BytesSerializer.RawMessage(
                        idBytes(7),
                        BigInteger.valueOf(1000),
                        "first-payload".getBytes(StandardCharsets.UTF_8),
                        new byte[0]),
                new BytesSerializer.RawMessage(
                        idBytes(8),
                        BigInteger.valueOf(1050),
                        "second-payload".getBytes(StandardCharsets.UTF_8),
                        "user-header-bytes".getBytes(StandardCharsets.UTF_8)));

        var batch = BytesSerializer.encodeBatch(messages);

        assertThat(ByteBufUtil.hexDump(batch)).isEqualTo(PRODUCE_BATCH_ONLY);
    }

    @Test
    void shouldDecodeGoldenPollBody() {
        var polled = BytesDeserializer.readPolledMessages(Unpooled.wrappedBuffer(ByteBufUtil.decodeHexDump(POLL_BODY)));

        assertThat(polled.partitionId()).isEqualTo(3L);
        assertThat(polled.currentOffset()).isEqualTo(BigInteger.valueOf(101));
        assertThat(polled.count()).isEqualTo(2L);
        assertThat(polled.messages()).hasSize(2);

        var first = polled.messages().get(0);
        assertThat(first.header().offset()).isEqualTo(BigInteger.valueOf(100));
        assertThat(first.header().timestamp()).isEqualTo(BigInteger.valueOf(5000));
        assertThat(first.header().originTimestamp()).isEqualTo(BigInteger.valueOf(1000));
        assertThat(first.header().id().toBigInteger()).isEqualTo(BigInteger.valueOf(7));
        assertThat(first.header().checksum()).isEqualTo(new BigInteger("7596755a20b9d2bf", 16));
        assertThat(first.payload()).isEqualTo("first-payload".getBytes(StandardCharsets.UTF_8));
        assertThat(first.userHeaders()).isEmpty();

        var second = polled.messages().get(1);
        assertThat(second.header().offset()).isEqualTo(BigInteger.valueOf(101));
        assertThat(second.header().timestamp()).isEqualTo(BigInteger.valueOf(5000));
        assertThat(second.header().originTimestamp()).isEqualTo(BigInteger.valueOf(1050));
        assertThat(second.header().id().toBigInteger()).isEqualTo(BigInteger.valueOf(8));
        assertThat(second.header().checksum()).isEqualTo(new BigInteger("c0b78e751c7e6bd6", 16));
        assertThat(second.payload()).isEqualTo("second-payload".getBytes(StandardCharsets.UTF_8));
        // The golden vector carries opaque non-TLV user header bytes: reported
        // by length, decoded to no entries.
        assertThat(second.header().userHeadersLength()).isEqualTo(17L);
        assertThat(second.userHeaders()).isEmpty();
    }

    @Test
    void shouldRoundTripBatchThroughPollDecoding() {
        var userHeaders =
                Map.of(HeaderKey.fromString("k1"), HeaderValue.fromRaw("v1".getBytes(StandardCharsets.UTF_8)));
        var batch = BytesSerializer.toMessagesBatch(
                List.of(message(100, 2000, "first", Map.of()), message(200, 2500, "second", userHeaders)));

        var polled = BytesDeserializer.readPolledMessages(pollBody(9, 1, 2, batch));

        assertThat(polled.messages()).hasSize(2);
        var first = polled.messages().get(0);
        assertThat(first.header().id().toBigInteger()).isEqualTo(BigInteger.valueOf(100));
        assertThat(first.header().offset()).isEqualTo(BigInteger.ZERO);
        assertThat(first.header().originTimestamp()).isEqualTo(BigInteger.valueOf(2000));
        assertThat(first.payload()).isEqualTo("first".getBytes(StandardCharsets.UTF_8));
        assertThat(first.userHeaders()).isEmpty();
        var second = polled.messages().get(1);
        assertThat(second.header().id().toBigInteger()).isEqualTo(BigInteger.valueOf(200));
        assertThat(second.header().offset()).isEqualTo(BigInteger.ONE);
        assertThat(second.header().originTimestamp()).isEqualTo(BigInteger.valueOf(2500));
        assertThat(second.payload()).isEqualTo("second".getBytes(StandardCharsets.UTF_8));
        assertThat(second.userHeaders().get(HeaderKey.fromString("k1")).asRaw())
                .isEqualTo("v1".getBytes(StandardCharsets.UTF_8));
    }

    @Test
    void shouldMintIdsForZeroIdMessages() {
        var batch = BytesSerializer.toMessagesBatch(List.of(Message.of("a"), Message.of("b")));

        var polled = BytesDeserializer.readPolledMessages(pollBody(1, 0, 2, batch));

        var firstId = polled.messages().get(0).header().id().toBigInteger();
        var secondId = polled.messages().get(1).header().id().toBigInteger();
        assertThat(firstId).isNotEqualTo(BigInteger.ZERO);
        assertThat(secondId).isNotEqualTo(BigInteger.ZERO);
        assertThat(firstId).isNotEqualTo(secondId);
    }

    @Test
    void shouldRejectEmptyBatch() {
        assertThatThrownBy(() -> BytesSerializer.toMessagesBatch(List.of()))
                .isInstanceOf(IggyInvalidArgumentException.class);
    }

    @Test
    void shouldRejectTimestampDeltaExceedingU32() {
        var messages = List.of(message(1, 0, "a", Map.of()), message(2, 0x1_0000_0000L, "b", Map.of()));

        assertThatThrownBy(() -> BytesSerializer.toMessagesBatch(messages))
                .isInstanceOf(IggyInvalidArgumentException.class);
    }

    @Test
    void shouldRejectNonZeroFrameReserved() {
        var body = ByteBufUtil.decodeHexDump(POLL_BODY);
        // Poll header (16) + batch header (256) + reserved offset inside the first frame (40).
        body[16 + 256 + 40] = 1;

        assertThatThrownBy(() -> BytesDeserializer.readPolledMessages(Unpooled.wrappedBuffer(body)))
                .isInstanceOf(IggyMalformedResponseException.class);
    }

    private static byte[] idBytes(long id) {
        return ByteBufUtil.getBytes(BytesSerializer.toBytesAsU128(BigInteger.valueOf(id)));
    }

    private static Message message(
            long id, long originTimestamp, String payload, Map<HeaderKey, HeaderValue> userHeaders) {
        var payloadBytes = payload.getBytes(StandardCharsets.UTF_8);
        var header = new MessageHeader(
                BigInteger.ZERO,
                new BigIntegerMessageId(BigInteger.valueOf(id)),
                BigInteger.ZERO,
                BigInteger.ZERO,
                BigInteger.valueOf(originTimestamp),
                0L,
                (long) payloadBytes.length,
                BigInteger.ZERO);
        return new Message(header, payloadBytes, userHeaders);
    }

    private static ByteBuf pollBody(long partitionId, long currentOffset, long count, ByteBuf batch) {
        var body = Unpooled.buffer(16 + batch.readableBytes());
        body.writeIntLE((int) partitionId);
        body.writeLongLE(currentOffset);
        body.writeIntLE((int) count);
        body.writeBytes(batch);
        return body;
    }
}
